### PR TITLE
added a optout field in settings

### PR DESCRIPTION
**Pull request by ammuiyer**

### CODE REVIEW

**Comment by ammuiyer** [comment]
Also added the question to opt in into git config alr.

**Review by ntdkhiem — COMMENTED** [review]
Await for User model and migration file.

**Comment by ntdkhiem** [comment]
- Added opted-in checkbox
- Updated User model with migration and validation

Need to work on opt-out feature.

**Review by ntdkhiem — APPROVED** [review]
lgtm

**Pull request merged**
